name: Deployment (Create)

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run deployment against'
          type: environment
          required: true

permissions:
  contents: read
  id-token: write

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

#      - name: Create
#        uses: azure/bicep-deploy@v1
#        with:
#          type: deployment
#          operation: create
#          name: Development
#          location: australiaeast
#          scope: resourceGroup
#          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
#          resource-group-name: rg-fedcourt
#          template-file: ./infra/main.bicep
#          parameters-file: ./infra/main.bicepparam
