name: Deployment (Create)

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run deployment against'
          type: environment
          required: true

permissions:
  contents: read
  id-token: write

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: validate
          name: Development
          location: australiaeast
          scope: subscription
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ./infra/main.bicep
          parameters-file: ./infra/main.bicepparam
  
      - name: What-If
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: whatIf
          name: Development
          location: australiaeast
          scope: subscription
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ./infra/main.bicep
          parameters-file: ./infra/main.bicepparam

      - name: Create
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: create
          name: Development
          location: australiaeast
          scope: subscription
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ./infra/main.bicep
          parameters: '{"environmentName": ${{ vars.AZURE_ENV_NAME }},"location": ${{ vars.AZURE_LOCATION }}, "sqlAdminPassword": ${{ vars.AZURE_SQLADMIN_PASSWORD }}, "sqlAdminUser": "sqladmin" }'

      - name: Start DB Migration
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://app-api-fedtest-a75x.azurewebsites.net/dbmigrate
          follow-redirect: false 
          max-attempts: 3 
          retry-delay: 5s 
          retry-all: false
          
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://app-api-fedtest-a75x.azurewebsites.net/todo
          follow-redirect: false 
          max-attempts: 3 
          retry-delay: 5s 
          retry-all: false
